Repository bsideproject/15_12_FE, pull requests merged in 2023-06, with the labels that each got.

#8 [Feat] 구글 소셜 로그인 변경 (endpoint -> amplify 방식)
  .gitignore
  amplify/.config/project-config.json
  amplify/backend/auth/1512fe199e37b1/parameters.json
  amplify/backend/awscloudformation/build/root-cloudformation-stack.json
  amplify/backend/backend-config.json
  amplify/backend/tags.json
  amplify/cli.json
  amplify/team-provider-info.json
  app/auth/callback/page.tsx
  aws-exports.js
  components/screen/Dashboard.tsx
  components/screen/Login.tsx
  hooks/useGoogleLogin.ts
  package.json
  yarn.lock
Labels: ✨ Feat

#9 [Feat/Design] : splash, on-boarding 추가 및 회원 관련 기능 재설정
  .eslintrc.json
  .vscode/settings.json
  amplify/.config/project-config.json
  amplify/backend/auth/1512fe199e37b1/parameters.json
  amplify/backend/backend-config.json
  amplify/team-provider-info.json
  app/(splash)/page.tsx
  app/auth/callback/page.tsx
  app/dashboard/page.tsx
  app/home/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/main/page.tsx
  app/on-boarding/page.tsx
  aws-exports.js
  components/screen/Dashboard.tsx
  components/screen/Home.tsx
  components/screen/Login.tsx
  components/screen/Main.tsx
  components/screen/Register.tsx
  components/screen/Splash.tsx
  components/screen/onBoarding.tsx
  constants/onBoardingText.ts
  core/interceptors.ts
  hooks/useGoogleLogin.ts
  next-svg.d.ts
  next.config.js
  package.json
  public/images/splash-logo.svg
  service/getUserAttributes.ts
  service/getUserInfo.ts
  service/getUserSession.ts
  service/mergeStyle.ts
  service/user.ts
  service/userPool.ts
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: 🎨 Design, ✨ Feat, 🔧 Chore

#12 [Update] : activity api call 및 token 수정 완료
  constants/activityFigcaption.tsx
  core/interceptors.ts
  service/getUserSession.ts
Labels: 🔨 Style

#13 [Feat/Design] : 로그인, 비밀번호 찾기 style 구현 및 관련 custom hook 추가
  .eslintrc.json
  app/forgot-pwd/page.tsx
  app/on-boarding/page.tsx
  components/elements/ElInput.tsx
  components/modules/ForgotPwdForm.tsx
  components/modules/PwdField.tsx
  components/modules/Sidebar.tsx
  components/screen/ForgotPwd.tsx
  components/screen/Home.tsx
  components/screen/Login.tsx
  components/screen/OnBoarding.tsx
  components/screen/Register.tsx
  components/screen/Splash.tsx
  constants/activityFigcaption.tsx
  core/interceptors.ts
  hooks/useNotify.ts
  hooks/useVh.ts
  layout/screen/Layout.tsx
  package.json
  public/images/activity01-icon.svg
  public/images/activity02-icon.svg
  public/images/activity03-icon.svg
  public/images/activity04-icon.svg
  public/images/back-sm-icon.svg
  public/images/google-icon.svg
  public/images/hide-password-icon.svg
  public/images/kakao-icon.svg
  public/images/mytemplate-icon.svg
  public/images/show-password-icon.svg
  public/images/splash-logo.svg
  public/images/test-img.svg
  queries/queryFn/useQueryActivities.ts
  service/getUserSession.ts
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: 🎨 Design, ✨ Feat

#14 [Design/Feat] : style 추가 적용 및 공통 components 추가
  .eslintrc.json
  components/elements/ElButton.tsx
  components/elements/ElGrid.tsx
  components/elements/ElInput.tsx
  components/modules/ActivityList.tsx
  components/modules/BackHead.tsx
  components/modules/ForgotPwdForm.tsx
  components/modules/FormField.tsx
  components/modules/HomeHead.tsx
  components/modules/LoginForm.tsx
  components/modules/LoginSocial.tsx
  components/modules/PwdField.tsx
  components/modules/Sidebar.tsx
  components/modules/Slider.tsx
  components/screen/ForgotPwd.tsx
  components/screen/Home.tsx
  components/screen/Login.tsx
  components/screen/OnBoarding.tsx
  components/screen/Register.tsx
  components/screen/Splash.tsx
  public/images/check-sm-icon.svg
  tailwind.config.js
Labels: 🎨 Design, ✨ Feat
