Repository bsideproject/15_12_FE, pull requests merged in 2023-07, with the labels that each got.

#15 [Chore/Feat] : 스피드 게임 방 만들기/조회 rest api 연결, 스타일 단위 변경
  app/speed-game/page.tsx
  app/start-game/page.tsx
  components/modules/GameInputs.tsx
  components/screen/SpeedGame.tsx
  components/screen/StartGame.tsx
  components/screen/speedGame.tsx
  components/screen/startGame.tsx
  package.json
  public/images/add-icon.svg
  public/images/game-icon.svg
  public/images/person-icon.svg
  yarn.lock
Labels: 🎨 Design, ✨ Feat, 🔧 Chore

#16 [Feat/Design] : acitivity 만들기, 조회 연결 및 style 반영
  app/loading.tsx
  app/mood-checkin/[start-game]/page.tsx
  app/mood-checkin/page.tsx
  app/not-found.tsx
  app/thank-circle/[start-game]/page.tsx
  app/thank-circle/page.tsx
  components/elements/ElGrid.tsx
  components/elements/ElInput.tsx
  components/modules/ActivityHead.tsx
  components/modules/ActivityList.tsx
  components/modules/CheckBox.tsx
  components/modules/ForgotPwdForm.tsx
  components/modules/FormField.tsx
  components/modules/HomeHead.tsx
  components/modules/PwdField.tsx
  components/modules/RegisterForm.tsx
  components/modules/Sidebar.tsx
  components/modules/Slider.tsx
  components/screen/Home.tsx
  components/screen/Loading.tsx
  components/screen/MoodCheckin.tsx
  components/screen/NotFound.tsx
  components/screen/Register.tsx
  components/screen/StartGames.tsx
  components/screen/ThankCircle.tsx
  constants/onBoardingText.ts
  hooks/useNavigation.ts
  package.json
  public/images/check-green-icon.svg
  public/images/loading-bg-img.svg
  public/images/loading-hand-img.svg
  public/images/mood-checkin-img.svg
  public/images/notfound-img.svg
  public/images/profile-icon.svg
  queries/apiKeys.ts
  queries/mutationFn/useMutationMoodCheckin.ts
  queries/mutationFn/useMutationThankCircle.ts
  queries/queryFn/useQueryMoodCheckin.ts
  queries/queryFn/useQueryThankCircle.ts
  queries/queryKeys.ts
  tailwind.config.js
  yarn.lock
Labels: 🎨 Design, ✨ Feat

#17 [Style/Feat] : 스피드 게임 공통 컴포넌트 적용/보완
  .eslintrc.json
  components/elements/EIIconInput.tsx
  components/elements/ElButton.tsx
  components/elements/ElGrid.tsx
  components/elements/ElQrImage.tsx
  components/modules/GameInputs.tsx
  components/modules/SpeedGameInputs.tsx
  components/screen/SpeedGame.tsx
  components/screen/StartGame.tsx
  public/images/activity01-sm-icon.svg
  public/images/check-blue-icon.svg
Labels: 🎨 Design, ✨ Feat

#18 [Feat/Design] : 기분 체크인 중간 배포
  app/mood-checkin/[room]/page.tsx
  app/mood-checkin/[room]/pick/page.tsx
  app/mood-checkin/[room]/progress/page.tsx
  app/mood-checkin/[start-game]/page.tsx
  app/mood-checkin/start-game/[room]/page.tsx
  app/thank-circle/[start-game]/page.tsx
  app/thank-circle/start-game/[room]/page.tsx
  components/elements/EIIconInput.tsx
  components/modules/FormField.tsx
  components/modules/StartTemplate.tsx
  components/modules/Wait.tsx
  components/screen/ParticipantNickname.tsx
  components/screen/Pick.tsx
  components/screen/StartGame/MoodCheckIn.tsx
  components/screen/StartGame/ThankCircle.tsx
  components/screen/StartGames.tsx
  components/screen/progress/MoodCheckin.tsx
  constants/moodCheckinArr.tsx
  hooks/useTest.ts
  next.config.js
  public/images/activity-logo.svg
  public/images/mood-checkin-icon01.svg
  public/images/mood-checkin-icon02.svg
  public/images/mood-checkin-icon03.svg
  public/images/mood-checkin-icon04.svg
  public/images/mood-checkin-icon05.svg
  public/images/wait-img.svg
  queries/mutationFn/useMutationMoodCheckin.ts
  queries/mutationFn/useMutationThankCircle.ts
  queries/queryFn/useQueryMoodCheckin.ts
  queries/queryFn/useQueryThankCircle.ts
  service/localStorage.ts
Labels: 🎨 Design, ✨ Feat

#19 [Fix] : socket 환경변수 변경
  hooks/useTest.ts
Labels: 🐞 Fix

#20 [Feat] : 감사서클 중간 배포
  app/mood-checkin/[room]/pick/page.tsx
  app/moodcheckin/[room]/page.tsx
  app/moodcheckin/[room]/progress/page.tsx
  app/moodcheckin/page.tsx
  app/moodcheckin/start-game/[room]/page.tsx
  app/thankcircle/[room]/page.tsx
  app/thankcircle/[room]/progress/page.tsx
  app/thankcircle/page.tsx
  app/thankcircle/start-game/[room]/page.tsx
  components/elements/ElGrid.tsx
  components/modules/ActivityList.tsx
  components/modules/MoodPick.tsx
  components/modules/StartTemplate.tsx
  components/modules/ThankList.tsx
  components/modules/ThankMixing.tsx
  components/modules/ThankTo.tsx
  components/modules/Wait.tsx
  components/screen/MoodCheckin.tsx
  components/screen/ParticipantNickname.tsx
  components/screen/StartGame/ThankCircle.tsx
  components/screen/ThankCircle.tsx
  components/screen/progress/MoodCheckin.tsx
  components/screen/progress/ThankCircle.tsx
  hooks/useTest.ts
  public/images/mixing-img.svg
  public/images/result-img.svg
  queries/mutationFn/useMutationMoodCheckin.ts
  queries/mutationFn/useMutationThankCircle.ts
  queries/queryFn/useQueryMoodCheckin.ts
  queries/queryFn/useQueryThankCircle.ts
Labels: 🎨 Design, ✨ Feat

#21 [Feat/Design] : 감사 서클 socket 연결 및 회원 탈퇴 추가
  app/layout.tsx
  atoms/userNickname.ts
  components/modules/Close.tsx
  components/modules/RegisterForm.tsx
  components/modules/Sidebar.tsx
  components/modules/Slider.tsx
  components/modules/StartTemplate.tsx
  components/modules/ThankList.tsx
  components/modules/ThankMixing.tsx
  components/modules/ThankTo.tsx
  components/modules/Wait.tsx
  components/screen/ParticipantNickname.tsx
  components/screen/StartGame/MoodCheckIn.tsx
  components/screen/StartGame/ThankCircle.tsx
  components/screen/progress/MoodCheckin.tsx
  components/screen/progress/ThankCircle.tsx
  hooks/useTest.ts
  layout/screen/Layout.tsx
  public/images/close-img.svg
  public/images/onboarding-img01.svg
  public/images/onboarding-img02.svg
  public/images/onboarding-img03.svg
Labels: 🎨 Design, ✨ Feat

#22 [Feat/Design] : 스피드 게임 웹소켓 배포 테스트
  app/speedgame/[room]/page.tsx
  app/speedgame/[room]/progress/page.tsx
  app/speedgame/page.tsx
  app/speedgame/start-game/[room]/page.tsx
  app/start-game/page.tsx
  components/elements/EIIconInput.tsx
  components/elements/ElQrImage.tsx
  components/modules/ActivityHead.tsx
  components/modules/ActivityList.tsx
  components/modules/GameImage.tsx
  components/modules/SpeedGameInputs.tsx
  components/modules/SpeedGameSelect.tsx
  components/modules/SpeedOpenAnswer.tsx
  components/modules/SpeedOpenQuestion.tsx
  components/modules/StartTemplate.tsx
  components/modules/Wait.tsx
  components/screen/ParticipantNickname.tsx
  components/screen/SpeedGame.tsx
  components/screen/StartGame.tsx
  components/screen/StartGame/SpeedGame.tsx
  components/screen/progress/SpeedGame.tsx
  hooks/useSocketHyo.ts
  public/images/check-blue-icon.svg
  public/images/check-bule-circle.svg
  public/images/check-grey-icon.svg
  public/images/game-icon.svg
  queries/apiKeys.ts
  queries/queryFn/useQuerySpeedGameCreate.ts
  queries/queryFn/useQuerySpeedGameGet.ts
  queries/queryKeys.ts
Labels: 🎨 Design, ✨ Feat

#24 [Update] : socket env 변경
  hooks/useSocket.ts
Labels: 🔨 Style

#26 [Fix] : socket 환경변수 변경
  hooks/useSocket.ts
Labels: 🐞 Fix

#27 [Feat/Design] : 미니 네트워킹 fix 및 기분 체크인 socket 로직 변경
  atoms/socketAtoms.ts
  components/modules/Close.tsx
  components/modules/MiniNetworkingResult.tsx
  components/modules/MoodCheckinPick.tsx
  components/screen/progress/MiniNetworking.tsx
  components/screen/progress/MoodCheckin.tsx
  hooks/useSocket.ts
Labels: 🎨 Design, ✨ Feat

#29 [Feat/Design] : 변경 디자인 적용 및 기분 체크인 fin
  components/modules/MiniNetworkingList.tsx
  components/modules/MiniNetworkingMatching.tsx
  components/modules/MiniNetworkingResult.tsx
  components/modules/MoodCheckinPick.tsx
  components/modules/MoodCheckinResult.tsx
  components/modules/StartTemplate.tsx
  components/modules/ThankCircleList.tsx
  components/modules/ThankCircleResult.tsx
  components/modules/Wait.tsx
  components/screen/MiniNetworking.tsx
  components/screen/MoodCheckin.tsx
  components/screen/ThankCircle.tsx
  components/screen/progress/MoodCheckin.tsx
  hooks/useSocket.ts
  public/images/mini-img.svg
  public/images/mini-logo.svg
  public/images/mood-img.svg
  public/images/mood-result-01.svg
  public/images/mood-result-02.svg
  public/images/mood-result-03.svg
  public/images/mood-result-04.svg
  public/images/mood-result-05.svg
  public/images/test-img.svg
  public/images/thank-button-icon.svg
  public/images/thank-img.svg
  public/images/thank-mood-logo.svg
Labels: 🎨 Design, ✨ Feat

#30 [Fix/Update] : socket 환경변수 변경, speedGame/home/policy 보완
  components/modules/ActivityList.tsx
  components/modules/CheckBox.tsx
  components/modules/RegisterForm.tsx
  components/screen/Policy.tsx
  components/screen/SpeedGame.tsx
  components/screen/StartGame/SpeedGame.tsx
  hooks/useSocket.ts
  hooks/useSocketHyo.ts
  public/images/users-icon.svg
  queries/apiKeys.ts
  queries/mutationFn/useMutationSpeedGame.ts
  queries/queryFn/useQuerySpeedGame.ts
  queries/queryFn/useQuerySpeedGameCreate.ts
  queries/queryKeys.ts
Labels: ✨ Feat, 🐞 Fix

#31 [Fix/Style] : 스피드 게임 정답자 배포 테스트
  app/mininetworking/start-game/[room]/page.tsx
  app/moodcheckin/start-game/[room]/page.tsx
  app/speedgame/start-game/[room]/page.tsx
  app/thankcircle/start-game/[room]/page.tsx
  components/elements/ElQrImage.tsx
  components/modules/SpeedOpenAnswer.tsx
  components/modules/SpeedOpenQuestion.tsx
  components/modules/StartTemplate.tsx
  components/screen/progress/SpeedGame.tsx
  components/screen/startGames/MiniNetworking.tsx
  components/screen/startGames/MoodCheckIn.tsx
  components/screen/startGames/SpeedGame.tsx
  components/screen/startGames/ThankCircle.tsx
  queries/queryFn/useQuerySpeedGame.ts
Labels: 🐞 Fix, 🔨 Style

#32 [Feat/Design/Refactor] 스피드 게임 제출자 기능, 게임 이미지 변경, 토스트 메시지 커스텀
  app/mininetworking/start-game/[room]/page.tsx
  app/moodcheckin/start-game/[room]/page.tsx
  app/speedgame/start-game/[room]/page.tsx
  app/thankcircle/start-game/[room]/page.tsx
  atoms/socketAtoms.ts
  components/modules/ActivityList.tsx
  components/modules/GameImage.tsx
  components/modules/MiniNetworkingList.tsx
  components/modules/MiniNetworkingResult.tsx
  components/modules/MoodCheckinPick.tsx
  components/modules/SpeedOpenQuestion.tsx
  components/modules/ThankCircleList.tsx
  components/screen/MiniNetworking.tsx
  components/screen/MoodCheckin.tsx
  components/screen/SpeedGame.tsx
  components/screen/ThankCircle.tsx
  components/screen/startGame/MiniNetworking.tsx
  components/screen/startGame/MoodCheckIn.tsx
  components/screen/startGame/SpeedGame.tsx
  components/screen/startGame/ThankCircle.tsx
  constants/activityFigcaption.tsx
  hooks/useSocket.ts
  layout/screen/Layout.tsx
  public/images/activity01-icon.svg
  public/images/activity01-sm-icon.svg
  public/images/activity02-icon.svg
  public/images/activity02-sm-icon.svg
  public/images/activity03-icon.svg
  public/images/activity03-sm-icon.svg
  public/images/activity04-icon.svg
  public/images/activity04-sm-icon.svg
  public/images/mini-img.svg
  public/images/mini-logo.svg
  public/images/mood-checkin-img.svg
  public/images/mood-img.svg
  public/images/thank-img.svg
  public/images/thank-mood-logo.svg
  styles/globals.css
Labels: 🎨 Design, ✨ Feat, ♻️ Refactor
