Repository bsideproject/15_12_FE, pull requests merged in 2023-05, with the labels that each got.

#1 [Feat] : migration 및 공용 기능 추가
  app/(home)/page.tsx
  app/layout.tsx
  app/loading.tsx
  app/not-found.tsx
  core/index.ts
  core/interceptors.ts
  hooks/useInput.ts
  hooks/useNavigation.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ✨ Feat, 🔧 Chore

#2 [Chore] : storybook, jest 패키지 추가
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  babel.config.js
  jest.config.js
  package.json
  yarn.lock
Labels: 🔧 Chore, 🧪 Test

#3 [Feat] : 회원가입 및 로그인 구현
  .eslintrc.json
  app/(home)/page.tsx
  app/(login)/page.tsx
  app/register/page.tsx
  components/elements/ElInput.tsx
  components/screen/Login.tsx
  components/screen/Register.tsx
  package.json
  styles/globals.css
  utils/userPool.ts
  yarn.lock
Labels: ✨ Feat

#4 [Feat] : 구글 소셜 로그인 구현
  README.md
  app/auth/callback/page.tsx
  app/dashboard/page.tsx
  components/screen/Dashboard.tsx
  components/screen/Login.tsx
  hooks/useGoogleLogin.ts
Labels: ✨ Feat, 📝 Docs

#5 [Feat] : 회원 관련 로직 추가 구현
  .eslintrc.json
  app/layout.tsx
  app/main/page.tsx
  components/screen/Login.tsx
  components/screen/Main.tsx
  components/screen/Register.tsx
  core/interceptors.ts
  service/getUserInfo.ts
  service/user.ts
  service/userPool.ts
Labels: ✨ Feat
